name: Build Nuget package

on:
  push:
    branches:
      - "master"

env:
  DOTNET_VERSION: '6.0.101'

jobs:
  build-package:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack --configuration Release --output .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: PekaVMClient
          path: "PekaVMClient.*.nupkg"